#%RAML 0.8
title: barnyard
baseUri: http://server/api/{version}
protocols: [ HTTPS ]
version: v0.1
mediaType: JSON
/census:
  displayName: census
  description: census of all animals
/inside/animal:
  displayName: resourceName
  description: markdown is OK
/outside/animal:
  displayName: resourceName

